name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

  schedule:
    - cron: "0 5 * * 4" # 5 o'clock utc on thursdays
jobs:
  build-test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add clippy

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: check (benches)
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --benches

      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: verify test vectors
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib --features verify-test-vectors

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -Dwarnings
  
  buildwasm:
    name: build wasm32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown 
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target wasm32-unknown-unknown --features wasm-bindgen